# Generated by Django 4.2.9 on 2024-07-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
