# Generated by Django 4.2.9 on 2024-07-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addmoney_info",
            name="add_money",
            field=models.CharField(
                choices=[("Expense", "Expense"), ("Income", "Income")],
                default="Expense",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Addmoney_info1",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "add_money",
                    models.CharField(
                        choices=[("Expense", "Expense"), ("Income", "Income")],
                        default="Income",
                        max_length=10,
                    ),
                ),
                ("quantity", models.BigIntegerField()),
                ("Date", models.DateField(default=django.utils.timezone.now)),
                (
                    "Category",
                    models.CharField(
                        choices=[
                            ("Monthly income", "Monthly income"),
                            ("Part Time Income", "Part Time Income"),
                        ],
                        default="Monthly income",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
